#!/usr/bin/env python3
"""Sheldon scoring auto-tuner.

Searches a small grid of base-weight candidates and ranks them by
out-of-sample synthetic PnL.  The best profile is written to
``profiles.tuned.json``; applying it to ``profiles.json`` is left to the
operator (``--apply`` does it for you, with a backup).

This is the feedback loop from layer 5: historical outcomes -> better weights.
It is intentionally conservative:

  - candidates are generated by small, bounded perturbations of the current
    base weights;
  - evaluation uses the *second half* of the scan history as a hold-out set,
    so the chosen profile is not just curve-fitted to the first half;
  - a candidate must improve both train and validation mean PnL over the
    current config to be recommended;
  - the default action is to print, not overwrite.

Usage:
    python3 tuner.py [--horizon 4] [--width 200] [--candidates 30]
                     [--data-dir /data/missy-data]
                     [--apply] [--output profiles.tuned.json]
"""

import argparse
import copy
import json
import os
import random
import sys
import time

import backtest
import lp_scoring

DEFAULT_DATA_DIR = "/data/missy-data"
DEFAULT_CANDIDATES = 30
DEFAULT_SEED = 42


def _make_args(data_dir, horizon, width):
    class _Args:
        pass
    args = _Args()
    args.data_dir = data_dir
    args.pools_dir = os.path.join(data_dir, "pool_screens")
    args.positions_dir = os.path.join(data_dir, "position_scans")
    args.horizon = horizon
    args.width = width
    args.position_value_usd = backtest.DEFAULT_POSITION_VALUE_USD
    args.entry_cost_bps = backtest.DEFAULT_ENTRY_COST_BPS
    args.exit_cost_bps = backtest.DEFAULT_EXIT_COST_BPS
    args.claim_cost_usd = backtest.DEFAULT_CLAIM_COST_USD
    args.bootstrap_samples = 1000
    args.seed = DEFAULT_SEED
    args.dynamic = True
    return args


def _pnl_summary(result):
    """Extract mean PnL, hit rate and max drawdown from backtest result."""
    overall = result.get("open_candidates", {}).get("overall", {})
    return {
        "mean_pnl_usd": overall.get("pnl_mean_usd"),
        "hit_rate_pct": overall.get("hit_rate_pct"),
        "max_drawdown_usd": overall.get("max_drawdown_usd"),
        "n": overall.get("n", 0),
    }


def _clone_weights(cfg):
    return {k: copy.deepcopy(v["weights"])
            for k, v in cfg["pool_profiles"].items()}


def _set_weights(cfg, weights):
    cfg = copy.deepcopy(cfg)
    for k, w in weights.items():
        cfg["pool_profiles"][k]["weights"] = copy.deepcopy(w)
    return cfg


def _generate_candidates(base_weights, rng, n=DEFAULT_CANDIDATES):
    """Produce small random perturbations of the base pool weights."""
    candidates = []
    components = {
        "stable_stable": ["fee_yield", "turnover", "depth", "depeg_safety", "volatility_fit"],
        "stable_bluechip": ["fee_yield", "turnover", "depth", "volatility_fit", "depeg_safety"],
        "bluechip_bluechip": ["fee_yield", "turnover", "depth", "volatility_fit"],
    }
    for i in range(n):
        w = copy.deepcopy(base_weights)
        for pair_class, comps in components.items():
            for comp in comps:
                if comp not in w[pair_class]:
                    continue
                # Perturb +/- up to 20 %, keeping weight non-negative.
                factor = 1.0 + rng.uniform(-0.2, 0.2)
                w[pair_class][comp] = max(0.0, w[pair_class][comp] * factor)
            # Renormalise to 100 (exact).
            total = sum(w[pair_class].values())
            if total <= 0:
                continue
            scaled = {c: v * 100.0 / total for c, v in w[pair_class].items()}
            rounded = {c: round(v, 2) for c, v in scaled.items()}
            diff = round(100.0 - sum(rounded.values()), 2)
            if diff:
                # Add the rounding error to the largest component.
                largest = max(rounded, key=rounded.get)
                rounded[largest] = round(rounded[largest] + diff, 2)
            w[pair_class] = rounded
        candidates.append({"weights": w, "name": f"candidate_{i + 1}"})
    return candidates


def _split_paths(paths, train_frac=0.8):
    split_idx = int(len(paths) * train_frac)
    if split_idx < 10 or len(paths) - split_idx < 5:
        return paths, []
    return paths[:split_idx], paths[split_idx:]


def _evaluate(cfg, paths, args):
    original = lp_scoring.get_config()
    try:
        lp_scoring.set_config(cfg)
        result = backtest.backtest_pools(paths, args)
        return _pnl_summary(result)
    finally:
        lp_scoring.set_config(original)


def tune(args):
    pool_paths = backtest.list_scans(args.pools_dir, "pool_scan")
    if len(pool_paths) < 20:
        print(f"too few scans: {len(pool_paths)}", file=sys.stderr)
        return 2

    base_cfg = lp_scoring.get_config()
    base_weights = _clone_weights(base_cfg)

    rng = random.Random(args.seed)
    candidates = _generate_candidates(base_weights, rng, args.candidates)

    train_paths, val_paths = _split_paths(pool_paths, args.train_frac)
    if not val_paths:
        print("insufficient scans for train/validation split", file=sys.stderr)
        return 2

    # Baseline on the same splits.
    base_train = _evaluate(base_cfg, train_paths, args)
    base_val = _evaluate(base_cfg, val_paths, args)
    baseline_score = (base_val.get("mean_pnl_usd") or -1e9)

    rows = []
    for cand in candidates:
        cfg = _set_weights(base_cfg, cand["weights"])
        train = _evaluate(cfg, train_paths, args)
        val = _evaluate(cfg, val_paths, args)
        rows.append({
            "name": cand["name"],
            "weights": cand["weights"],
            "train": train,
            "val": val,
            "score": (val.get("mean_pnl_usd") or -1e9),
        })

    # Keep candidates that beat baseline on validation; sort by validation PnL.
    rows = [r for r in rows if r["score"] > baseline_score]
    rows.sort(key=lambda r: r["score"], reverse=True)

    best = rows[0] if rows else None

    output = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S+08:00"),
        "baseline": {"train": base_train, "val": base_val},
        "best": best,
        "candidates": rows[:10],
    }

    out_path = args.output
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(output, fh, indent=2)
        fh.write("\n")

    if best:
        print(f"Best candidate: {best['name']}")
        print(f"  train mean_pnl = ${best['train']['mean_pnl_usd']}  n={best['train']['n']}")
        print(f"  val   mean_pnl = ${best['val']['mean_pnl_usd']}  n={best['val']['n']}")
        print(f"  baseline val   = ${base_val.get('mean_pnl_usd')}")
        print(f"Recommendation written to {out_path}")
        if args.apply:
            backup = f"profiles.json.bak.{int(time.time())}"
            os.replace("profiles.json", backup)
            new_cfg = _set_weights(base_cfg, best["weights"])
            with open("profiles.json", "w", encoding="utf-8") as fh:
                json.dump(new_cfg, fh, indent=2)
                fh.write("\n")
            print(f"Applied; backup: {backup}")
    else:
        print("No candidate beat the baseline on validation.")
        print(f"Results written to {out_path}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Tune Sheldon scoring weights")
    ap.add_argument("--data-dir", default=DEFAULT_DATA_DIR)
    ap.add_argument("--pools-dir", default=None)
    ap.add_argument("--horizon", type=int, default=4)
    ap.add_argument("--width", type=int, default=200)
    ap.add_argument("--candidates", type=int, default=DEFAULT_CANDIDATES)
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--train-frac", type=float, default=0.8)
    ap.add_argument("--output", default="profiles.tuned.json")
    ap.add_argument("--apply", action="store_true",
                    help="overwrite profiles.json with the best candidate")
    args = ap.parse_args()
    if args.pools_dir is None:
        args.pools_dir = os.path.join(args.data_dir, "pool_screens")
    # Ensure backtest args carry cost defaults.
    for attr, default in (
        ("position_value_usd", backtest.DEFAULT_POSITION_VALUE_USD),
        ("entry_cost_bps", backtest.DEFAULT_ENTRY_COST_BPS),
        ("exit_cost_bps", backtest.DEFAULT_EXIT_COST_BPS),
        ("claim_cost_usd", backtest.DEFAULT_CLAIM_COST_USD),
        ("bootstrap_samples", 1000),
        ("seed", DEFAULT_SEED),
        ("dynamic", True),
    ):
        if not hasattr(args, attr):
            setattr(args, attr, default)
    return tune(args)


if __name__ == "__main__":
    sys.exit(main())
